# Generated by Django 2.2.12 on 2021-07-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_follow_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
    ]
